# This is a basic workflow to help you get started with Actions
# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  runs-on: ubuntu-latest
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # run shellcheck
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
